"""
station_baselines.py
Station-specific THD baselines for anomaly detection.

Each station has different characteristics (local geology, installation, noise).
Instead of universal THD thresholds, we use station-specific baselines and
detect anomalies as z-scores (standard deviations above baseline).

Baselines are established from quiet periods (no known precursors).
Values should be updated periodically as more data is collected.

Author: R.J. Mathews
Date: January 2026
"""

from dataclasses import dataclass
from typing import Dict, Optional
import json
from pathlib import Path
import logging

logger = logging.getLogger(__name__)
# The dated rolling-recal files (run_thd_recal writes thd_baselines_<YYYYMMDD>.json here); tests override it.
BASELINE_DIR = Path(__file__).resolve().parent.parent / 'data' / 'baselines'


@dataclass
class StationBaseline:
    """Baseline statistics for a single station."""
    station: str  # e.g., "IU.ANTO"
    mean_thd: float  # Average THD during quiet period
    std_thd: float  # Standard deviation of THD
    n_samples: int  # Number of days in baseline
    calibration_period: str  # e.g., "2025-06-01 to 2025-12-31"
    notes: str = ""
    # calibration-eligibility-v3 (prospective; read only by the eligibility rule, which is OFF): the day the
    # baseline was CALIBRATED, as a structured field, so the R3 30-day lag can be re-checked without reading notes.
    # None = unknown (the built-in 2026-01 defaults). Set by _load_newest_baseline_file from the dated file name.
    calibration_date: Optional[str] = None
    # thd-daily-measurement-v1 staged comparability (codex cfb195ff): the calibration CONVENTION the recal stamped into
    # the entry; None = legacy (every file written before the shared measurement). Read by ensemble.thd_support only.
    calibration_convention: Optional[str] = None


# Auto-calibrated station baselines (January 2026)
# Generated by: python calibrate_thd_baselines.py --days 30
# Uses robust statistics (median + MAD*1.4826)
STATION_BASELINES: Dict[str, StationBaseline] = {
    # IU Network (40Hz)
    'IU.TUC': StationBaseline(
        station='IU.TUC',
        mean_thd=0.340665,
        std_thd=0.039952,
        n_samples=31,
        calibration_period='2025-12-10 to 2026-01-09',
        notes='Auto-calibrated. QA=acceptable. Serves ridgecrest, socal_saf_mojave, socal_saf_coachella.'
    ),
    'IU.COR': StationBaseline(
        station='IU.COR',
        mean_thd=0.28278,
        std_thd=0.046364,
        n_samples=31,
        calibration_period='2025-12-10 to 2026-01-09',
        notes='Auto-calibrated. QA=acceptable. Cascadia subduction zone.'
    ),
    'IU.MAJO': StationBaseline(
        station='IU.MAJO',
        mean_thd=0.308837,
        std_thd=0.030176,
        n_samples=31,
        calibration_period='2025-12-10 to 2026-01-09',
        notes='Auto-calibrated. QA=acceptable. Tokyo/Kanto fallback (until Hi-net).'
    ),
    'IU.ANTO': StationBaseline(
        station='IU.ANTO',
        mean_thd=0.41292,
        std_thd=0.153212,
        n_samples=30,
        calibration_period='2025-12-10 to 2026-01-09',
        notes='Auto-calibrated. QA=acceptable. Serves istanbul_marmara, turkey_kahramanmaras.'
    ),
    'IU.TATO': StationBaseline(
        station='IU.TATO',
        mean_thd=0.338773,
        std_thd=0.037314,
        n_samples=32,
        calibration_period='2025-12-09 to 2026-01-09',
        notes='Auto-calibrated. QA=acceptable. Serves hualien region (Taiwan).'
    ),
    'IU.COLA': StationBaseline(
        station='IU.COLA',
        mean_thd=0.183849,
        std_thd=0.039561,
        n_samples=32,
        calibration_period='2025-12-09 to 2026-01-09',
        notes='Auto-calibrated. QA=acceptable. Fallback for anchorage (AK.SSL unavailable).'
    ),

    # BK Network (40Hz) - Berkeley
    'BK.BKS': StationBaseline(
        station='BK.BKS',
        mean_thd=0.305512,
        std_thd=0.049728,
        n_samples=31,
        calibration_period='2025-12-10 to 2026-01-09',
        notes='Auto-calibrated. QA=acceptable. NorCal Hayward fault.'
    ),

    # GE Network (20Hz) - GEOFON - Separate baselines due to different sample rate
    'GE.ARPR': StationBaseline(
        station='GE.ARPR',
        mean_thd=1.00,  # UNCALIBRATED - manual estimate
        std_thd=0.30,
        n_samples=7,
        calibration_period='2026-01-01 to 2026-01-07',
        notes='UNCALIBRATED. Arapgir, Turkey. Do not compare to IU stations.'
    ),
    'GE.CSS': StationBaseline(
        station='GE.CSS',
        mean_thd=0.20,  # UNCALIBRATED - manual estimate
        std_thd=0.06,
        n_samples=7,
        calibration_period='2026-01-01 to 2026-01-07',
        notes='UNCALIBRATED. Cyprus. Moderate baseline.'
    ),

    # IV Network - Campi Flegrei (requires INGV access - not available via IRIS)
    # 'IV.CAFE': Not available - requires direct INGV access

    # IU Network - New Zealand (IRIS accessible)
    'IU.SNZO': StationBaseline(
        station='IU.SNZO',
        mean_thd=0.30,  # UNCALIBRATED - estimate based on similar IU broadband
        std_thd=0.07,   # Conservative estimate
        n_samples=0,
        calibration_period='UNCALIBRATED',
        notes='UNCALIBRATED. South Karori, Wellington NZ. Only IRIS station in NZ for Kaikoura.'
    ),

    # NZ Network (GeoNet New Zealand) - Not accessible via IRIS
    # Kept for reference but requires GeoNet FDSN endpoint
    # 'NZ.HSES': Not accessible via IRIS - requires GeoNet
    # 'NZ.WEL': Not accessible via IRIS - requires GeoNet
    # 'NZ.BKZ': Not accessible via IRIS - requires GeoNet

    # AK Network (Alaska) - Added January 2026
    'AK.SSL': StationBaseline(
        station='AK.SSL',
        mean_thd=0.25,  # UNCALIBRATED
        std_thd=0.06,
        n_samples=0,
        calibration_period='UNCALIBRATED',
        notes='UNCALIBRATED. South Sled, AK. Primary for Anchorage.'
    ),

    # MX Network (Mexico) - Added January 2026
    'MX.TLIG': StationBaseline(
        station='MX.TLIG',
        mean_thd=0.135859,
        std_thd=0.04906,
        n_samples=87,
        calibration_period='2025-10-19 to 2026-01-17',
        notes='Auto-calibrated. QA=acceptable. Guerrero subduction zone. P95=0.2025'
    ),
}


def calibration_date_from_name(name: str) -> Optional[str]:
    """calibration-eligibility-v3: the calibration day encoded in a run_thd_recal file name
    (`thd_baselines_<YYYYMMDD>.json`, named by the recal's end date), as 'YYYY-MM-DD'; None when the name does not
    carry a valid calendar date. Never guesses."""
    from datetime import datetime as _dt
    stem = Path(name).stem
    if not stem.startswith('thd_baselines_'):
        return None
    digits = stem[len('thd_baselines_'):][:8]
    if len(digits) != 8 or not digits.isdigit():
        return None
    try:
        return _dt.strptime(digits, '%Y%m%d').strftime('%Y-%m-%d')
    except ValueError:
        return None


def _baseline_from_entry(e, filename):
    """Shared loader/snapshot parser; a malformed row never selects a newer file."""
    if e.get('mean_thd') is None or e.get('std_thd') is None:
        raise ValueError('missing baseline moments')
    effective_date = e.get('calibration_date')
    if not isinstance(effective_date, str) or len(effective_date) != 10:
        effective_date = calibration_date_from_name(filename)
    return StationBaseline(
        station=e['station'], mean_thd=float(e['mean_thd']), std_thd=float(e['std_thd']),
        n_samples=int(e.get('n_samples') or e.get('n_days_valid') or 0),
        calibration_period=e.get('calibration_period', 'unknown'),
        notes=f"Rolling recal, loaded newest-first from {filename}", calibration_date=effective_date,
        calibration_convention=(e.get('calibration_convention') if isinstance(e.get('calibration_convention'), str)
                                else None))


def _load_newest_baseline_file(bdir: Optional[Path] = None) -> Optional[str]:
    """INCIDENT 2026-07-31 (D1) newest-first load: override the hardcoded (2026-01) defaults above with the
    freshest dated rolling-recal file `data/baselines/thd_baselines_*.json`, so the weekly R3 recal is picked
    up automatically without editing this module. Fully defensive: tries files newest-first, accepts either
    the flat `{key:{...}}` or the calibration `{baselines:[{station,...}]}` format, skips malformed/None
    entries, and if nothing loads it leaves the built-in defaults in place (the ensemble staleness guard then
    catches those). Never raises. Returns the filename used, or None.
    `bdir` (calibration-eligibility-v3) overrides the directory for tests only; production passes nothing."""
    try:
        if bdir is None:
            bdir = BASELINE_DIR
        files = sorted(bdir.glob('thd_baselines_*.json'), key=lambda p: p.name, reverse=True)  # newest name first
    except Exception:
        return None
    for f in files:
        try:
            with open(f) as fh:
                data = json.load(fh)
        except Exception as e:
            logger.warning(f"THD baseline file {f.name} unreadable ({e}); trying older / built-in defaults")
            continue
        if isinstance(data, dict) and isinstance(data.get('baselines'), list):
            entries = data['baselines']
        elif isinstance(data, dict):
            entries = [v for v in data.values() if isinstance(v, dict) and 'station' in v]
        else:
            entries = []
        loaded = 0
        for e in entries:
            try:
                parsed = _baseline_from_entry(e, f.name)
                STATION_BASELINES[parsed.station] = parsed
                loaded += 1
            except Exception:
                continue
        if loaded:
            logger.info(f"Loaded {loaded} THD baselines from {f.name} (newest-first, incident 2026-07-31)")
            return f.name
    logger.info("No loadable dated THD baseline file; using built-in defaults (staleness guard applies)")
    return None


# thd-baseline-as-of-v1: the built-in defaults exactly as written above, kept before the import-time load overrides them,
# so a scored day falls back to them the way the loader does.
_BUILTIN_BASELINES: Dict[str, StationBaseline] = dict(STATION_BASELINES)

# Apply newest-first load at import: the freshest rolling recal overrides the built-in 2026-01 defaults.
_NEWEST_BASELINE_FILE = _load_newest_baseline_file()


def _file_baselines(path) -> Optional[Dict[str, StationBaseline]]:
    """The baselines one dated file holds, parsed exactly as the newest-first loader parses them: None when the file is
    unreadable, {} when it holds no valid entry."""
    try:
        with open(path) as fh:
            data = json.load(fh)
    except Exception:
        return None
    if isinstance(data, dict) and isinstance(data.get('baselines'), list):
        entries = data['baselines']
    elif isinstance(data, dict):
        entries = [v for v in data.values() if isinstance(v, dict) and 'station' in v]
    else:
        entries = []
    held = {}
    for e in entries:
        try:
            parsed = _baseline_from_entry(e, Path(path).name)
            held[parsed.station] = parsed
        except Exception:
            continue
    return held


def _scored_day(as_of) -> str:
    """'YYYY-MM-DD' for a date, datetime or ISO date string; anything else is refused (never guessed)."""
    from datetime import datetime as _dt
    text = as_of.strftime('%Y-%m-%d') if hasattr(as_of, 'strftime') else as_of
    if not isinstance(text, str) or len(text) != 10:
        raise ValueError('BASELINE_AS_OF_NOT_A_DAY: %r' % (as_of,))
    return _dt.strptime(text, '%Y-%m-%d').strftime('%Y-%m-%d')


def baseline_as_of(station_code: str, network: str, as_of, bdir: Optional[Path] = None) -> Optional[StationBaseline]:
    """thd-baseline-as-of-v1 (cayley 2026-10-09; run da191bd4): the baseline IN FORCE for scored day `as_of`.

    The newest-first rule of the import-time loader, restricted to the dated files that existed for that day: the
    newest readable file named `thd_baselines_<YYYYMMDD>.json` whose date is ON OR BEFORE the scored day; a station
    that file lacks keeps its built-in default, as at import. A file named after the scored day (a later recal) is
    never used for it -- with scoring two days behind, the same-run recal would otherwise be the newest file, and the
    registered lag (calibration_eligibility) refuses it on every recal day and the day after. No such file: the
    built-in default. The import-time selection (STATION_BASELINES) is unchanged for every other caller."""
    day = _scored_day(as_of)
    key = f"{network}.{station_code}"
    try:
        files = sorted((bdir or BASELINE_DIR).glob('thd_baselines_*.json'), key=lambda p: p.name, reverse=True)
    except Exception:
        files = []
    for f in files:
        file_day = calibration_date_from_name(f.name)
        if file_day is None or file_day > day:
            continue
        held = _file_baselines(f)
        if not held:   # unreadable, or no valid entry: the loader tries the next older file too
            continue
        return held.get(key, _BUILTIN_BASELINES.get(key))
    return _BUILTIN_BASELINES.get(key)


def get_baseline(station_code: str, network: str, as_of=None) -> Optional[StationBaseline]:
    """
    Get baseline for a station.

    Args:
        station_code: Station code (e.g., 'ANTO')
        network: Network code (e.g., 'IU')
        as_of: the scored day (thd-baseline-as-of-v1): the baseline in force for that day; None = the import-time
            newest-first selection, unchanged

    Returns:
        StationBaseline or None if not found
    """
    if as_of is not None:
        return baseline_as_of(station_code, network, as_of)
    key = f"{network}.{station_code}"
    return STATION_BASELINES.get(key)


def compute_z_score(thd_value: float, baseline: StationBaseline) -> float:
    """
    Compute z-score (anomaly score) relative to baseline.

    Returns number of standard deviations above the mean.
    Negative values mean below average (normal).
    Values > 2 are significant anomalies.
    Values > 3 are critical anomalies.
    """
    if baseline.std_thd <= 0:
        return 0.0

    z = (thd_value - baseline.mean_thd) / baseline.std_thd
    return z


def z_score_to_risk(z_score: float) -> float:
    """
    Convert z-score to 0-1 risk score.

    Mapping:
        z < 0: risk = 0.0-0.1 (below baseline)
        z = 0-1: risk = 0.1-0.25 (normal variation)
        z = 1-2: risk = 0.25-0.50 (elevated)
        z = 2-3: risk = 0.50-0.75 (significant anomaly)
        z > 3: risk = 0.75-1.0 (critical anomaly)
    """
    if z_score < 0:
        return max(0.0, 0.1 + z_score * 0.05)  # Clamp to 0
    elif z_score < 1:
        return 0.1 + z_score * 0.15
    elif z_score < 2:
        return 0.25 + (z_score - 1) * 0.25
    elif z_score < 3:
        return 0.50 + (z_score - 2) * 0.25
    else:
        return min(1.0, 0.75 + (z_score - 3) * 0.08)  # Cap at 1.0


def is_baseline_available(station_code: str, network: str) -> bool:
    """Check if baseline is available for station."""
    key = f"{network}.{station_code}"
    return key in STATION_BASELINES


def save_baselines_to_file(filepath: Path):
    """Save current baselines to JSON file."""
    data = {}
    for key, baseline in STATION_BASELINES.items():
        data[key] = {
            'station': baseline.station,
            'mean_thd': baseline.mean_thd,
            'std_thd': baseline.std_thd,
            'n_samples': baseline.n_samples,
            'calibration_period': baseline.calibration_period,
            'notes': baseline.notes
        }

    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2)

    logger.info(f"Saved {len(data)} station baselines to {filepath}")


def load_baselines_from_file(filepath: Path) -> bool:
    """Load baselines from JSON file, updating the global dict."""
    global STATION_BASELINES

    if not filepath.exists():
        logger.warning(f"Baseline file not found: {filepath}")
        return False

    try:
        with open(filepath, 'r') as f:
            data = json.load(f)

        for key, values in data.items():
            STATION_BASELINES[key] = StationBaseline(
                station=values['station'],
                mean_thd=values['mean_thd'],
                std_thd=values['std_thd'],
                n_samples=values['n_samples'],
                calibration_period=values['calibration_period'],
                notes=values.get('notes', '')
            )

        logger.info(f"Loaded {len(data)} station baselines from {filepath}")
        return True

    except Exception as e:
        logger.error(f"Error loading baselines: {e}")
        return False


# Print summary when imported
if __name__ == "__main__":
    print("Station Baselines Summary")
    print("=" * 70)
    print(f"{'Station':<12} {'Mean THD':>10} {'Std':>8} {'N':>5} {'Notes'}")
    print("-" * 70)
    for key, b in sorted(STATION_BASELINES.items()):
        print(f"{b.station:<12} {b.mean_thd:>10.4f} {b.std_thd:>8.4f} {b.n_samples:>5} {b.notes[:30]}")
